### ISSUE TITLE
Add preview.

### ISSUE THREAD

**Issue by jaccarmac** [StickmanVentures/lol-csv#9]
Add ability to preview results in simple Bootstrap grid.

https://www.reddit.com/r/leagueoflegends/comments/44uag4/download_a_spreadsheet_with_your_ranked_game_stats/czsybsg

http://bl.ocks.org/ndarville/7075823

https://d3js.org/

**Comment by Reshurum** [comment]
I started working on this, but the csv has a lot of columns so the table is pushed. As far as I know, overflow does not work with tables as you cannot constrain a table's width.
